name: CI workflow

# Events
on: push

# List of jobs
jobs:
  test:
    # runner
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
